#!/bin/bash

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

pattern="^(ADD|FIX|FEAT|UPDATE): .+"

if ! [[ $commit_msg =~ $pattern ]]; then
  echo "Invalid commit message!"
  echo "Allowed format:"
  echo "ADD: message"
  echo "FIX: message"
  echo "FEAT: message"
  echo "UPDATE: message"
  exit 1
fi
